### PR TITLE
fix communication with debuggserver on ios-14

### LINKED ISSUE #469: Can not start com.apple.debugserver on iOS 14 device under Xcode 12.0 beta 4
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Don't forget to check out the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue

The same thread in the libimobiledevice side: https://github.com/libimobiledevice/libimobiledevice/issues/1004

# Expected behavior

Install the app successfully and launch the app on the device

# Actual behavior.

The command failed with "Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)"

# Steps to reproduce the problem

1. Connect to an iOS 14 device and use Xcode 12.0 beta4
2. Run `ios-deploy -d -b {Bundle.app}` 

# System Specs

macOS 15.5
Xcode 12.0
Build version 12A8179i

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
- [ ] 2. ios-deploy -V
- [ ] 3. xcodebuild -version
- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version
- [ ] **If using NodeJS/npm**
  - [ ] 7. npm -v
  - [ ] 8. node -v

### PR DESCRIPTION
**Pull request by Ukalnins**
Should fix #469 . 
If I did not mess anything up by merging changes this should work on older and newer ios devices.
Added also the version detection for tvOS, but I don't have a device to test this.

### CODE REVIEW

**Comment by gabebear** [comment]
II was trying to test this and it seems like the debugger never connects(it copies and starts services properly). I'm testing with:
 - iPhoneXs-Max running  iOS14 beta6(18A5357e)
 - MacBook Pro running macOS 10.15.6(19G2021)
 - Xcode 12 beta6(12A8189n)

What is your setup?

File: src/ios-deploy/ios-deploy.m [hunk 1]
```diff
@@ -1037,15 +1065,15 @@ void start_remote_debug_server(AMDeviceRef device) {
...
-    assert(con != NULL);
-    gdbfd = AMDServiceConnectionGetSocket(con);
+    assert(dbgServiceConnection != NULL);
+
     /*
      * The debugserver connection is through a fd handle, while lldb requires a host/port to connect, so create an intermediate
      * socket to transfer data.
      */
-    server_socket = CFSocketCreateWithNative (NULL, gdbfd, kCFSocketDataCallBack, &server_callback, NULL);
+    server_socket = CFSocketCreateWithNative (NULL, AMDServiceConnectionGetSocket(dbgServiceConnection), kCFSocketDataCallBack, &server_callback, NULL);
```
Comment (ivanhernandez13) [inline src/ios-deploy/ios-deploy.m:1076]: You might need to change to this to subscribe to kCFSocketReadCallBack. kCFSocketDataCallBack will consume the incoming data so AMDServiceConnectionReceive will hang because no data is left. kCFSocketReadCallBack will be called when data is available to read but won't read it.

**Comment by ivanhernandez13** [comment]
Thanks for the patch! I was working on a similar patch and I was having the same issue with the debugserver not connecting. I left a comment on the line that resolved my issue.

File: src/ios-deploy/ios-deploy.m (hunk 1 above)
Comment (jmagman) [reply src/ios-deploy/ios-deploy.m:1076]: I just tried this patch with `kCFSocketDataCallBack` and the debugger successfully connected.

Comment (ivanhernandez13) [reply src/ios-deploy/ios-deploy.m:1076]: That's interesting, on my setup this patch does not work for the reason mentioned above.

Do you mind sharing your setup? I have:

- iPad Air 2 running iOS14 beta 6 (18A5357e)
- iMac Pro running macOS 10.15.6 (19G73)
- Xcode 12.0 beta 6 (12A8189n)

Comment (Ukalnins) [reply src/ios-deploy/ios-deploy.m:1076]: Yeah, it should be kCFSocketReadCallBack.  Got lost while fixing merge conflicts. I'll fix the pull request tomorrow.

File: src/ios-deploy/ios-deploy.m [hunk 2]
```diff
@@ -959,13 +963,27 @@ void write_lldb_prep_cmds(AMDeviceRef device, CFURLRef disk_app_url) {
 void
 server_callback (CFSocketRef s, CFSocketCallBackType callbackType, CFDataRef address, const void *data, void *info)
 {
-    if (CFDataGetLength (data) == 0) {
+    char buffer[0x4000];
```
Comment (ivanhernandez13) [inline src/ios-deploy/ios-deploy.m:966]: Is there a particular reason for this value?

From sniffing the packets, they don't seem to be very large. Plus looks like the while loop should handle larger packets.

Regardless of the size we should memset to null characters.

File: src/ios-deploy/ios-deploy.m [hunk 3]
```diff
@@ -959,13 +963,27 @@ void write_lldb_prep_cmds(AMDeviceRef device, CFURLRef disk_app_url) {
...
+    if (bytesRead == 0)
+    {
         // close the socket on which we've got end-of-file, the server_socket.
         CFSocketInvalidate(s);
         CFRelease(s);
         return;
     }
-    write(CFSocketGetNative(lldb_socket), CFDataGetBytePtr(data), CFDataGetLength(data));
+    write(CFSocketGetNative (lldb_socket), buffer, bytesRead);
+    if (bytesRead == sizeof(buffer))
```
Comment (ivanhernandez13) [inline src/ios-deploy/ios-deploy.m:976]: Should this be: `while (bytesRead == sizeof(buffer)) { ... }`?

If we get a packet where size = $BUF_SIZE + 1, this will:
- read $BUF_SIZE bytes
- write $BUF_SIZE bytes to socket
- read 1 byte
- write 1 byte to socket
- wait to read more data which may not be there 

With the singular while loop we can stop reading after we've consumed all the data.

File: src/ios-deploy/ios-deploy.m [hunk 4]
```diff
@@ -959,13 +963,27 @@ void write_lldb_prep_cmds(AMDeviceRef device, CFURLRef disk_app_url) {
...
+    {
+        while (bytesRead > 0)
+        {
+            bytesRead = AMDServiceConnectionReceive(dbgServiceConnection, buffer, sizeof(buffer));
```
Comment (ivanhernandez13) [inline src/ios-deploy/ios-deploy.m:980]: Should also memset before reusing.

**Comment by jmagman** [comment]
This seems to be working (with the `kCFSocketReadCallBack` change) on a wirelessly tethered device, but I'm still seeing `0xe8000022` on a wirelessly paired device (Connect via network).  The app installs correctly.
```
[ +501 ms] ------ Debug phase ------
[        ] Starting debug of device-id (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'iPhone 6s' connected through WIFI...
[+2287 ms] [  0%] Looking up developer disk image
[ +141 ms] [ 95%] Developer disk image mounted successfully
[  +67 ms] Failed to start debugserver: e8000022 The service is invalid.
```
The same app and device work when Xcode launches.

File: src/ios-deploy/ios-deploy.m (hunk 4 above)
Comment (Ukalnins) [reply src/ios-deploy/ios-deploy.m:980]: No point in memsetting as we are always working with ptr + length not c strings. There is no benefit from memeset, only extra work.

File: src/ios-deploy/ios-deploy.m (hunk 2 above)
Comment (Ukalnins) [reply src/ios-deploy/ios-deploy.m:966]: It's nicer to handle everything in single read call, as I have some doubts in properly separating errors and no more data cases. Return value of 0 bytes mean both - ssl error and no more bytes. 

What I saw was mostly around 200-300 byte packets, but when large amount of stdout is printed, I did saw it climb to up to 3000 bytes.  Though I agree, 16 kb is a bit large, my intention was more in 4 kb.

File: src/ios-deploy/ios-deploy.m (hunk 3 above)
Comment (Ukalnins) [reply src/ios-deploy/ios-deploy.m]: Yeah, removed the redundant if in favor of while.

Comment (Ukalnins) [reply src/ios-deploy/ios-deploy.m]: Yeah, removed the redundant if in favor of while.

**Comment by gabebear** [comment]
We should probably focus on getting wired debugging working first since it’s blocking many flows. We can always open another issue for iOS14 wireless debugging.

**Comment by Ukalnins** [comment]
Hmm, cannot repeat the WIFI problem. Works fine for me on an 5th gen iPad mini. @jmagman , can you add some debug logging, which service is ios-deploy trying to start? Maybe version detection in some cases is not working properly.

**Comment by Ukalnins** [comment]
It seems there was regression on iOS 13 and older devices, as it needed dropping SSL connection now and the `AMDeviceIsAtLeastVersionOnPlatform` was actually returning `bool`. 😅

File: src/ios-deploy/ios-deploy.m (hunk 4 above)
Comment (ivanhernandez13) [reply src/ios-deploy/ios-deploy.m]: Oops, you're right. Was assuming we were strlen'ing the buffer when writing back out but bytesRead already gives that information.

**Comment by gabebear** [comment]
I tested the latest fixes on an Apple-Silicon DTK and everything is working:
 - wired iOS14b6 iPhone XS 
 - wireless iOS14b6 iPhone XS
 - wired iOS12.4.8 iPad mini2

This looks good, great work!

**Comment by ivanhernandez13** [comment]
Can confirm patch works fine for me as well on iOS 14b6 iPad Air 2 and iOS 13.6.1 iPhone XS Max. Both wired and wirelessly.

**Comment by christopherfujino** [comment]
@ivanhernandez13 @Ukalnins thanks so much for this fix!

**Comment by ryanluoo** [comment]
@Ukalnins Hi I just found out you have changed the definition of `service_conn_t`  in `MobileDevice.h`.

This will cause `AFCConnectionOpen` to fail.   Can you help to fix this ?

**Comment by Ukalnins** [comment]
Hi, I'm using `AFCConnectionOpen` and it works. Can you expand on what macOS, iOS and XCode version combination you are seeing this and  why you think that the exact change is the cause? Maybe you can create a bug report for this, as this PL is already closed.
