### PR TITLE
Show finer progress when installing

### LINKED ISSUE #514: Installation seems stuck when the bundle has a large file
Instalation seems stuck when the bundle has a large file. Seems like we print the progress only once for a path when installing. The issue with this is that if we have a large file in the bundle, the progress seems stuck for a long time without any feedback. 

# Expected behavior
 Finer progress should be logged 

# Actual behavior.
It gets stuck without any logs for some time when a large file is being copied. After the copy, the percentage jumps by a large number suddenly. 

# Steps to reproduce the problem
Try installing a bundle which has one large file (few hundred MBs).

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Fix #514: Installation seems stuck when the bundle has a large file

Print message when overall progress percentage changes.

### CODE REVIEW

File: src/ios-deploy/ios-deploy.m [hunk 1]
```diff
@@ -718,9 +719,9 @@ mach_error_t transfer_callback(CFDictionaryRef dict, int arg) {
 
     if (CFEqual(status, CFSTR("CopyingFile"))) {
         CFStringRef path = CFDictionaryGetValue(dict, CFSTR("Path"));
+        int overall_percent = percent / 2;
 
-        if ((last_path == NULL || !CFEqual(path, last_path)) && !CFStringHasSuffix(path, CFSTR(".ipa"))) {
-            int overall_percent = percent / 2;
```
Comment (gabebear) [inline src/ios-deploy/ios-deploy.m:723]: Since **`last_overall_percent`** really only pertains to this BundleCopy phase I think it would make more sense to make it a `static` variable rather than a global.

**Review by gabebear — CHANGES_REQUESTED** [review]
Thanks, this makes sense so we don't spam with the same percent.

**Comment by nisargjhaveri** [comment]
@gabebear Thanks for the suggestion. Updated.

File: src/ios-deploy/ios-deploy.m (hunk 1 above)
Comment (nisargjhaveri) [reply src/ios-deploy/ios-deploy.m:723]: Moved `last_path` as well to make it static.

Comment (gabebear) [reply src/ios-deploy/ios-deploy.m:723]: Thanks
